In [2]:
import numpy as np

class HebbianLearning:
    def __init__(self, input_size, output_size, learning_rate=0.1):
        self.weights = np.zeros((output_size, input_size))
        self.learning_rate = learning_rate

    def train(self, inputs, outputs, epochs=1):
        for epoch in range(epochs):
            for x, y in zip(inputs, outputs):
                delta_w = self.learning_rate * np.outer(y, x)
                self.weights += delta_w

    def predict(self, x):
        return np.dot(self.weights, x)

if __name__ == "__main__":
    # Define training inputs (4 samples, 3 features)
    inputs = np.array([[1, 0, 1],
                       [0, 1, 0],
                       [1, 1, 0],
                       [0, 0, 1]])

    # Define target outputs (4 samples, 2 output neurons)
    outputs = np.array([[1, 0],
                        [0, 1],
                        [1, 0],
                        [0, 1]])

    print("=== Training Data ===")
    print("Inputs:")
    print(inputs)
    print("Target Outputs:")
    print(outputs)

    # Initialize Hebbian model
    model = HebbianLearning(input_size=3, output_size=2, learning_rate=0.1)

    # Train the model
    model.train(inputs, outputs, epochs=10)

    print("\n=== Learned Weights ===")
    print(model.weights)

    print("\n=== Predictions on Training Data ===")
    for i, x in enumerate(inputs):
        predicted = model.predict(x)
        target = outputs[i]

        # Because outputs can be continuous values, apply a simple threshold to get predicted class (0 or 1)
        predicted_binary = (predicted > 0.5).astype(int)

        print(f"Input: {x}")
        print(f"Target Output: {target}")
        print(f"Predicted Output (raw): {predicted}")
        print(f"Predicted Output (binary): {predicted_binary}")
        print(f"Match Target? {np.array_equal(predicted_binary, target)}")
        print("-" * 30)


=== Training Data ===
Inputs:
[[1 0 1]
 [0 1 0]
 [1 1 0]
 [0 0 1]]
Target Outputs:
[[1 0]
 [0 1]
 [1 0]
 [0 1]]

=== Learned Weights ===
[[2. 1. 1.]
 [0. 1. 1.]]

=== Predictions on Training Data ===
Input: [1 0 1]
Target Output: [1 0]
Predicted Output (raw): [3. 1.]
Predicted Output (binary): [1 1]
Match Target? False
------------------------------
Input: [0 1 0]
Target Output: [0 1]
Predicted Output (raw): [1. 1.]
Predicted Output (binary): [1 1]
Match Target? False
------------------------------
Input: [1 1 0]
Target Output: [1 0]
Predicted Output (raw): [3. 1.]
Predicted Output (binary): [1 1]
Match Target? False
------------------------------
Input: [0 0 1]
Target Output: [0 1]
Predicted Output (raw): [1. 1.]
Predicted Output (binary): [1 1]
Match Target? False
------------------------------
